var nt_settings = {
  theme_ver: "Kalles Shopify v1.5.1",
  scrollTop: 100,
  pjaxTimeout: 5e3,
  dragThreshold: 10,
  backtop: "3",
  pagination: null,
  review: !1,
  app_review: "3",
  ajax_scroll: !1,
  ajax_shop: !0,
  ajax_scroll_offset: "100",
  ntla_ck: !1,
  pr_curent: "3",
  use_clicking_vimg: !1,
  PleaseChoosePrOptions:
    "Selecione algumas op\xE7\xF5es de produto antes de adicionar este produto ao seu carrinho.",
  enableHistoryState: !1,
  pr_incoming_mess: !1,
  use_notify_me: !1,
  use_vimg: !0,
  use_sticky_des: !0,
  wishlist_type: "1",
  type_filters: "1",
  auto_hide_ofsock: !1,
  show_hide_ofsock: !1,
  added_to_cart: "Adicionado ao carrinho",
  view_cart: "Veja o carrinho",
  continue_shopping: "Continue comprando",
  save_js: "-[sale]%",
  disOnlyStock: !1,
  disATCerror: !1,
  close: "Close (Esc)",
  share_fb: "Share on Facebook",
  pin_it: "Pin it",
  tweet: "Tweet",
  download_image: "Download image",
  img_captions: !0,
  z_magnify: 2,
  z_touch: !1,
  galleryType: "pswp",
  maxSpreadZoom: 1,
  bgOpacity: 1,
  currencies: !0,
  currency_visitor: !1,
  currency_format: "money_format",
  round_currency: !1,
  hover_currency: !1,
  remove_currency: !1,
  round_cur_shop: !1,
  after_action_atc: "4",
  ins_host: "https://d3ejra0xbg20rg.cloudfront.net",
  bannerCountdown: "%D days %H:%M:%S",
  prItemCountdown: "%D Days %H:%M:%S",
  countdown_days: "dias",
  countdown_hours: "horas",
  countdown_mins: "minutos",
  countdown_sec: "segundos",
  multiple_rates:
    "Encontramos [number_of_rates] diferentes fretes para seu endere\xE7o[address], come\xE7ando por [rate].",
  one_rate:
    "Achamos uma op\xE7\xE3o de frete dispon\xEDvel para o seu endere\xE7o",
  no_rates: "Desculpe, n\xE3o podemos enviar para o seu endere\xE7o",
  rate_value: "[rate_title] por [rate]",
  agree_checkout:
    "Voc\xEA precisa concordar com termos e condi\xE7\xF5es antes do checkout",
  zoom_tp: "2",
  search_prefix: "*",
  platform_email: "1",
  checkbox_mail: !1,
  edit_item: "0",
};
//# sourceMappingURL=/cdn/shop/t/4/assets/nt_settings.js.map?v=171438126776805009351756000283
